# Generated by Django 3.2.23 on 2024-03-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '尊享版')], default=1, verbose_name='收费类型')),
                ('title', models.CharField(max_length=16, verbose_name='类型')),
                ('prices', models.PositiveIntegerField(verbose_name='价格/年')),
                ('create_project_num', models.PositiveIntegerField(verbose_name='创建项目个数')),
                ('project_member_num', models.PositiveIntegerField(verbose_name='每个项目最大成员数')),
                ('space_size', models.PositiveIntegerField(verbose_name='每个项目空间大小')),
                ('file_size', models.PositiveIntegerField(verbose_name='单文件大小')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=16, verbose_name='项目名')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目描述')),
                ('color', models.SmallIntegerField(choices=[(1, '#56b8eb'), (2, '#f28033'), (3, '#ebc656'), (4, '#a2d148'), (5, '#20BFA4'), (6, '#7461c2'), (7, '#20bfa3')], default=1, verbose_name='颜色')),
                ('start', models.BooleanField(default=False, verbose_name='星标')),
                ('use_space', models.IntegerField(default=0, verbose_name='项目使用空间')),
                ('participants_num', models.IntegerField(default=1, verbose_name='参与人数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户名')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('MobelPhone', models.CharField(max_length=12, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='交易状态')),
                ('order', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('true_pay', models.IntegerField(verbose_name='实际付款')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('quantity', models.IntegerField(verbose_name='数量/年')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.fees', verbose_name='价格')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='project_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False, verbose_name='星标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='参与者')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='create_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='创建人'),
        ),
    ]
