# Generated by Django 3.2.23 on 2024-03-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('father_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.wiki', verbose_name='父文章')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目名')),
            ],
        ),
    ]
