# Generated by Django 3.2.23 on 2024-03-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='father_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.wiki', verbose_name='父文章'),
        ),
    ]
