# Generated by Django 3.2.23 on 2024-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='xxx', max_length=128, verbose_name='桶名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='ap_chengdu', max_length=32, verbose_name='cos区域'),
            preserve_default=False,
        ),
    ]
