# Generated by Django 3.2.23 on 2024-03-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_filerepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='单文件大小/m'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='space_size',
            field=models.PositiveIntegerField(verbose_name='每个项目空间大小/m'),
        ),
        migrations.AlterField(
            model_name='filerepository',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='文件大小/m'),
        ),
        migrations.AlterField(
            model_name='filerepository',
            name='name',
            field=models.CharField(help_text='文件/文件夹名', max_length=256, verbose_name='文件夹名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_space',
            field=models.BigIntegerField(default=0, help_text='字节', verbose_name='项目使用空间'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='模块名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='IssuesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='类型名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80, verbose_name='问题名称')),
                ('desc', models.TextField(verbose_name='问题描述')),
                ('priority', models.CharField(choices=[('danger', '高'), ('warning', '中'), ('success', '低')], default='danger', max_length=12, verbose_name='优先级')),
                ('status', models.SmallIntegerField(choices=[(1, '新建'), (2, '处理中'), (3, '已解决'), (4, '已忽略'), (5, '待反馈'), (6, '已关闭'), (7, '重新打开')], default=1, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('mode', models.SmallIntegerField(choices=[(1, '公开模式'), (2, '隐私模式')], default=1, verbose_name='模式')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('latest_update_datetime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='web.userinfo', verbose_name='指派')),
                ('attention', models.ManyToManyField(blank=True, related_name='observe', to='web.UserInfo', verbose_name='关注者')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_problems', to='web.userinfo', verbose_name='创建者')),
                ('issues_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.issuestype', verbose_name='问题类型')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.module', verbose_name='模块')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='web.issues', verbose_name='父问题')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目')),
            ],
        ),
    ]
