# Generated by Django 3.2.23 on 2024-03-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_projectinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvite',
            name='count',
        ),
    ]
